from pathlib import Path

js=Path('app.js')
s=js.read_text()
s=s.replace("const state=PRODUCTS.map(product=>({grind:product.defaultGrind,purchase:'subscribe',bags:1,discount:10,qty:1}));", "const state=PRODUCTS.map(product=>({grind:product.defaultGrind,purchase:'subscribe',bags:1,discount:10,qty:1,image:0}));")
old='''        <div class="coffee-gallery"><div class="gallery-stack">\n          <figure class="product-frame"><img data-front src="${pair[0]}" alt="${product.name} front"></figure>\n          <figure class="product-frame product-frame--secondary"><img data-back src="${pair[1]}" alt="${product.name} back"></figure>\n        </div></div>'''
new='''        <div class="coffee-gallery"><div class="gallery-stack">\n          <div class="image-carousel" data-image-carousel>\n            <figure class="product-frame"><img data-carousel-image src="${pair[0]}" alt="${product.name} product view"></figure>\n            <div class="product-dots" role="tablist" aria-label="Product images">\n              <button class="product-dot is-active" type="button" data-image-dot="0" aria-label="Show front image" aria-selected="true"></button>\n              <button class="product-dot" type="button" data-image-dot="1" aria-label="Show back image" aria-selected="false"></button>\n            </div>\n          </div>\n        </div></div>'''
if old not in s: raise SystemExit('gallery template not found')
s=s.replace(old,new,1)
oldfn="function updateImages(index){const slide=slides[index];const product=PRODUCTS[index];const pair=product.images[state[index].grind]||product.images[product.defaultGrind];slide.querySelector('[data-front]').src=pair[0];slide.querySelector('[data-back]').src=pair[1]}"
newfn='''function updateImages(index,animate=false){\n    const slide=slides[index];\n    const product=PRODUCTS[index];\n    const current=state[index];\n    const pair=product.images[current.grind]||product.images[product.defaultGrind];\n    const image=slide.querySelector('[data-carousel-image]');\n    const next=pair[current.image]||pair[0];\n    if(!image)return;\n    const apply=()=>{image.src=next;image.alt=`${product.name} ${current.image===0?'front':'back'}`};\n    if(!animate){apply()}else{\n      image.getAnimations().forEach(animation=>animation.cancel());\n      const out=image.animate([{opacity:1,transform:'translateX(0) scale(1)'},{opacity:0,transform:`translateX(${current.image===0?'18px':'-18px'}) scale(.985)`}],{duration:180,easing:'ease',fill:'forwards'});\n      out.addEventListener('finish',()=>{\n        apply();\n        out.cancel();\n        image.animate([{opacity:0,transform:`translateX(${current.image===0?'-18px':'18px'}) scale(.985)`},{opacity:1,transform:'translateX(0) scale(1)'}],{duration:520,easing:'cubic-bezier(.16,1,.3,1)'});\n      },{once:true});\n    }\n    slide.querySelectorAll('[data-image-dot]').forEach(dot=>{const active=Number(dot.dataset.imageDot)===current.image;dot.classList.toggle('is-active',active);dot.setAttribute('aria-selected',String(active))});\n  }\n\n  function setImage(index,imageIndex){\n    const next=Math.max(0,Math.min(1,imageIndex));\n    if(state[index].image===next)return;\n    state[index].image=next;\n    updateImages(index,true);\n  }'''
if oldfn not in s: raise SystemExit('updateImages not found')
s=s.replace(oldfn,newfn,1)
needle="""    const toggle=event.target.closest('[data-toggle-details]');if(toggle){event.preventDefault();if(slide.classList.contains('is-detail'))closeDetails(index);else openDetails(index);return}\n    const grind=event.target.closest('[data-grind]');"""
replacement="""    const toggle=event.target.closest('[data-toggle-details]');if(toggle){event.preventDefault();if(slide.classList.contains('is-detail'))closeDetails(index);else openDetails(index);return}\n    const imageDot=event.target.closest('[data-image-dot]');if(imageDot){setImage(index,Number(imageDot.dataset.imageDot));return}\n    const grind=event.target.closest('[data-grind]');"""
if needle not in s: raise SystemExit('click insertion point not found')
s=s.replace(needle,replacement,1)
needle2="""  addEventListener('scroll',onScroll,{passive:true});"""
swipe='''  slides.forEach((slide,index)=>{\n    const carousel=slide.querySelector('[data-image-carousel]');\n    if(!carousel)return;\n    let startX=0,startY=0,tracking=false;\n    carousel.addEventListener('pointerdown',event=>{if(!slide.classList.contains('is-detail'))return;tracking=true;startX=event.clientX;startY=event.clientY;carousel.setPointerCapture?.(event.pointerId)});\n    carousel.addEventListener('pointerup',event=>{if(!tracking)return;tracking=false;const dx=event.clientX-startX;const dy=event.clientY-startY;if(Math.abs(dx)>46&&Math.abs(dx)>Math.abs(dy)*1.25)setImage(index,dx<0?1:0)});\n    carousel.addEventListener('pointercancel',()=>{tracking=false});\n  });\n\n  addEventListener('scroll',onScroll,{passive:true});'''
if needle2 not in s: raise SystemExit('scroll insertion point not found')
s=s.replace(needle2,swipe,1)
js.write_text(s)

css=Path('style.css')
c=css.read_text()
c=c.replace('.gallery-stack{height:100%}\n.product-frame{', '.gallery-stack{height:100%}\n.image-carousel{position:relative;width:100%;height:100%;touch-action:pan-y}\n.product-dots{position:absolute;left:50%;bottom:clamp(30px,5svh,58px);z-index:5;display:flex;align-items:center;gap:10px;transform:translateX(-50%);opacity:0;pointer-events:none;transition:opacity 360ms ease}\n.product-dot{width:9px;height:9px;padding:0;border:1px solid rgba(255,255,255,.72);border-radius:50%;background:transparent;cursor:pointer;transition:width 380ms var(--ease),border-radius 380ms var(--ease),background 280ms ease,opacity 280ms ease}\n.product-dot.is-active{width:26px;border-radius:999px;background:#fff;border-color:#fff}\n.product-frame{',1)
old='''.coffee-slide.is-detail .coffee-gallery{position:relative;height:auto;min-height:200svh;overflow:visible;align-self:start;padding-top:0}\n.coffee-slide.is-detail .gallery-stack{height:auto;min-height:200svh}\n.coffee-slide.is-detail .product-frame{position:relative;top:auto;height:100svh}\n.coffee-slide.is-detail .product-frame--secondary{display:grid;z-index:auto}'''
new='''.coffee-slide.is-detail .coffee-gallery{position:sticky;top:0;height:100svh;min-height:100svh;overflow:hidden;align-self:start;padding-top:0}\n.coffee-slide.is-detail .gallery-stack{height:100svh;min-height:100svh}\n.coffee-slide.is-detail .image-carousel{height:100svh}\n.coffee-slide.is-detail .product-frame{position:relative;top:auto;height:100svh}\n.coffee-slide.is-detail .product-dots{opacity:1;pointer-events:auto}'''
if old not in c: raise SystemExit('desktop gallery detail block not found')
c=c.replace(old,new,1)
oldm='''.coffee-slide.is-detail .coffee-gallery{position:relative;height:auto;min-height:136svh;overflow:visible;padding-top:0}.coffee-slide.is-detail .product-frame{position:relative;top:auto;height:68svh}.coffee-slide.is-detail .product-frame img{max-height:60svh}'''
newm='''.coffee-slide.is-detail .coffee-gallery{position:sticky;top:0;height:58svh;min-height:58svh;overflow:hidden;padding-top:0}.coffee-slide.is-detail .gallery-stack,.coffee-slide.is-detail .image-carousel{height:58svh;min-height:58svh}.coffee-slide.is-detail .product-frame{position:relative;top:auto;height:58svh}.coffee-slide.is-detail .product-frame img{max-height:52svh}.coffee-slide.is-detail .product-dots{bottom:18px}'''
if oldm not in c: raise SystemExit('mobile gallery detail block not found')
c=c.replace(oldm,newm,1)
css.write_text(c)
