from pathlib import Path

js=Path('app.js')
s=js.read_text()

old='''          <div class="image-carousel" data-image-carousel>\n            <figure class="product-frame"><img data-carousel-image src="${pair[0]}" alt="${product.name} product view"></figure>\n            <button class="carousel-arrow carousel-arrow--prev" type="button" data-image-prev aria-label="Previous product image"><span class="material-icons" aria-hidden="true">chevron_left</span></button>\n            <button class="carousel-arrow carousel-arrow--next" type="button" data-image-next aria-label="Next product image"><span class="material-icons" aria-hidden="true">chevron_right</span></button>\n            <div class="product-dots" role="tablist" aria-label="Product images">\n              <button class="product-dot is-active" type="button" data-image-dot="0" aria-label="Show front image" aria-selected="true"></button>\n              <button class="product-dot" type="button" data-image-dot="1" aria-label="Show back image" aria-selected="false"></button>\n            </div>\n          </div>'''
new='''          <div class="image-carousel" data-image-carousel>\n            <div class="image-viewport">\n              <div class="image-track" data-image-track>\n                <figure class="product-frame image-panel"><img data-carousel-image="0" src="${pair[0]}" alt="${product.name} front"></figure>\n                <figure class="product-frame image-panel"><img data-carousel-image="1" src="${pair[1]}" alt="${product.name} back"></figure>\n              </div>\n            </div>\n            <button class="carousel-arrow carousel-arrow--prev" type="button" data-image-prev aria-label="Previous product image"><span class="material-icons" aria-hidden="true">chevron_left</span></button>\n            <button class="carousel-arrow carousel-arrow--next" type="button" data-image-next aria-label="Next product image"><span class="material-icons" aria-hidden="true">chevron_right</span></button>\n            <div class="product-dots" role="tablist" aria-label="Product images">\n              <button class="product-dot is-active" type="button" data-image-dot="0" aria-label="Show front image" aria-selected="true"></button>\n              <button class="product-dot" type="button" data-image-dot="1" aria-label="Show back image" aria-selected="false"></button>\n            </div>\n          </div>'''
if old not in s: raise SystemExit('carousel template block not found')
s=s.replace(old,new,1)

start=s.index('  function updateImages(index,animate=false){')
end=s.index('\n\n  function updatePurchase(index){',start)
replacement='''  function updateImages(index,animate=false){\n    const slide=slides[index];\n    const product=PRODUCTS[index];\n    const current=state[index];\n    const pair=product.images[current.grind]||product.images[product.defaultGrind];\n    const images=[...slide.querySelectorAll('[data-carousel-image]')];\n    const trackEl=slide.querySelector('[data-image-track]');\n    images.forEach((image,imageIndex)=>{\n      const src=pair[imageIndex]||pair[0];\n      image.src=src;\n      image.alt=`${product.name} ${imageIndex===0?'front':'back'} · ${current.grind}`;\n    });\n    if(trackEl){\n      trackEl.style.setProperty('--image-index',String(current.image));\n      trackEl.classList.toggle('is-instant',!animate);\n      if(!animate)requestAnimationFrame(()=>trackEl.classList.remove('is-instant'));\n    }\n    slide.querySelectorAll('[data-image-dot]').forEach(dot=>{\n      const active=Number(dot.dataset.imageDot)===current.image;\n      dot.classList.toggle('is-active',active);\n      dot.setAttribute('aria-selected',String(active));\n    });\n  }\n\n  function setImage(index,imageIndex){\n    const next=Math.max(0,Math.min(1,imageIndex));\n    if(state[index].image===next)return;\n    state[index].image=next;\n    updateImages(index,true);\n  }'''
s=s[:start]+replacement+s[end:]

start=s.index('  function closeDetails(index){')
end=s.index('\n\n  track.addEventListener',start)
replacement='''  function finishClose(index){\n    const slide=slides[index];\n    const shell=slide.querySelector('.copy-shell');\n    const toggle=slide.querySelector('[data-toggle-details]');\n    if(!shell)return;\n\n    const current=shell.getBoundingClientRect();\n    const probe=shell.cloneNode(true);\n    probe.querySelector('.detail-content')?.remove();\n    probe.style.cssText=`position:fixed;left:${current.left}px;top:-10000px;width:${current.width}px;transform:none;visibility:hidden;pointer-events:none;`;\n    document.body.appendChild(probe);\n    const collapsedHeight=probe.getBoundingClientRect().height;\n    probe.remove();\n\n    const targetTop=(innerHeight-collapsedHeight)/2;\n    const dy=targetTop-current.top;\n    slide.classList.add('is-closing');\n    if(toggle)toggle.textContent='View Details';\n    shell.getAnimations().forEach(animation=>animation.cancel());\n    const animation=shell.animate(\n      [{transform:'translateY(0)'},{transform:`translateY(${dy}px)`}],\n      {duration:820,easing:'cubic-bezier(.16,1,.3,1)',fill:'forwards'}\n    );\n    animation.addEventListener('finish',()=>{\n      slide.classList.remove('is-closing','is-detail');\n      document.body.classList.remove('details-open');\n      slide.scrollTop=0;\n      animation.cancel();\n      detailIndex=-1;\n    },{once:true});\n  }\n\n  function closeDetails(index){\n    const slide=slides[index];\n    if(slide.classList.contains('is-closing'))return;\n    const startTop=slide.scrollTop;\n    if(startTop<=2){finishClose(index);return}\n\n    const duration=Math.min(650,Math.max(360,startTop*.35));\n    const started=performance.now();\n    slide.classList.add('is-returning');\n    const ease=t=>1-Math.pow(1-t,4);\n    const step=now=>{\n      const t=Math.min(1,(now-started)/duration);\n      slide.scrollTop=startTop*(1-ease(t));\n      if(t<1){requestAnimationFrame(step);return}\n      slide.scrollTop=0;\n      slide.classList.remove('is-returning');\n      finishClose(index);\n    };\n    requestAnimationFrame(step);\n  }'''
s=s[:start]+replacement+s[end:]

old="const grind=event.target.closest('[data-grind]');if(grind){current.grind=grind.dataset.grind;slide.querySelectorAll('[data-grind]').forEach(btn=>btn.classList.toggle('is-selected',btn===grind));updateImages(index);return}"
new="const grind=event.target.closest('[data-grind]');if(grind){current.grind=grind.dataset.grind;slide.querySelectorAll('[data-grind]').forEach(btn=>btn.classList.toggle('is-selected',btn===grind));updateImages(index,false);return}"
if old not in s: raise SystemExit('grind handler not found')
s=s.replace(old,new,1)

old="  PRODUCTS.forEach((_,index)=>updatePurchase(index));\n  requestAnimationFrame(renderHorizontal);"
new="  PRODUCTS.forEach((_,index)=>{updatePurchase(index);updateImages(index,false)});\n  requestAnimationFrame(renderHorizontal);"
if old not in s: raise SystemExit('initialization block not found')
s=s.replace(old,new,1)
js.write_text(s)

css=Path('style.css')
c=css.read_text()
old='.image-carousel{position:relative;width:100%;height:100%;touch-action:pan-y}'
new='.image-carousel{position:relative;width:100%;height:100%;touch-action:pan-y;user-select:none}.image-viewport{position:relative;width:100%;height:100%;overflow:hidden}.image-track{--image-index:0;display:flex;width:200%;height:100%;transform:translate3d(calc(var(--image-index) * -50%),0,0);transition:transform 760ms cubic-bezier(.16,1,.3,1);will-change:transform}.image-track.is-instant{transition:none}.image-panel{flex:0 0 50%;width:50%}'
if old not in c: raise SystemExit('image carousel css not found')
c=c.replace(old,new,1)

c=c.replace('.coffee-slide.is-detail .gallery-stack{height:100svh;min-height:100svh}\n.coffee-slide.is-detail .image-carousel{height:100svh}', '.coffee-slide.is-detail .gallery-stack{height:100svh;min-height:100svh}\n.coffee-slide.is-detail .image-carousel,.coffee-slide.is-detail .image-viewport,.coffee-slide.is-detail .image-track{height:100svh}',1)
c=c.replace('.coffee-slide.is-detail .gallery-stack,.coffee-slide.is-detail .image-carousel{height:58svh;min-height:58svh}', '.coffee-slide.is-detail .gallery-stack,.coffee-slide.is-detail .image-carousel,.coffee-slide.is-detail .image-viewport,.coffee-slide.is-detail .image-track{height:58svh;min-height:58svh}',1)
c=c.replace('.coffee-slide.is-detail.is-closing .detail-content{', '.coffee-slide.is-detail.is-returning .view-details{pointer-events:none;opacity:.55}\n.coffee-slide.is-detail.is-closing .detail-content{',1)
css.write_text(c)
