from pathlib import Path

js=Path('app.js')
s=js.read_text()
old='''            <figure class="product-frame"><img data-carousel-image src="${pair[0]}" alt="${product.name} product view"></figure>\n            <div class="product-dots" role="tablist" aria-label="Product images">'''
new='''            <figure class="product-frame"><img data-carousel-image src="${pair[0]}" alt="${product.name} product view"></figure>\n            <button class="carousel-arrow carousel-arrow--prev" type="button" data-image-prev aria-label="Previous product image"><span class="material-icons" aria-hidden="true">chevron_left</span></button>\n            <button class="carousel-arrow carousel-arrow--next" type="button" data-image-next aria-label="Next product image"><span class="material-icons" aria-hidden="true">chevron_right</span></button>\n            <div class="product-dots" role="tablist" aria-label="Product images">'''
if old not in s: raise SystemExit('carousel markup insertion point not found')
s=s.replace(old,new,1)
old='''    const imageDot=event.target.closest('[data-image-dot]');if(imageDot){setImage(index,Number(imageDot.dataset.imageDot));return}\n    const grind=event.target.closest('[data-grind]');'''
new='''    const imageDot=event.target.closest('[data-image-dot]');if(imageDot){setImage(index,Number(imageDot.dataset.imageDot));return}\n    if(event.target.closest('[data-image-prev]')){setImage(index,state[index].image===0?1:0);return}\n    if(event.target.closest('[data-image-next]')){setImage(index,state[index].image===1?0:1);return}\n    const grind=event.target.closest('[data-grind]');'''
if old not in s: raise SystemExit('carousel click insertion point not found')
s=s.replace(old,new,1)
js.write_text(s)

css=Path('style.css')
c=css.read_text()
old='''.image-carousel{position:relative;width:100%;height:100%;touch-action:pan-y}\n.product-dots{position:absolute;left:50%;bottom:clamp(30px,5svh,58px);z-index:5;display:flex;align-items:center;gap:10px;transform:translateX(-50%);opacity:0;pointer-events:none;transition:opacity 360ms ease}\n.product-dot{width:9px;height:9px;padding:0;border:1px solid rgba(255,255,255,.72);border-radius:50%;background:transparent;cursor:pointer;transition:width 380ms var(--ease),border-radius 380ms var(--ease),background 280ms ease,opacity 280ms ease}\n.product-dot.is-active{width:26px;border-radius:999px;background:#fff;border-color:#fff}'''
new='''.image-carousel{position:relative;width:100%;height:100%;touch-action:pan-y}\n.carousel-arrow{position:absolute;top:50%;z-index:6;width:52px;height:52px;padding:0;border:1px solid rgba(255,255,255,.18);border-radius:50%;background:rgba(255,255,255,.08);color:#fff;display:grid;place-items:center;opacity:0;transform:translateY(-50%) scale(.92);cursor:pointer;backdrop-filter:blur(10px);transition:opacity 260ms ease,transform 360ms var(--ease),background 260ms ease,border-color 260ms ease}\n.carousel-arrow--prev{left:clamp(22px,3vw,52px)}\n.carousel-arrow--next{right:clamp(22px,3vw,52px)}\n.carousel-arrow .material-icons{font-size:30px}\n.image-carousel:hover .carousel-arrow{opacity:1;transform:translateY(-50%) scale(1)}\n.carousel-arrow:hover{background:rgba(255,255,255,.16);border-color:rgba(255,255,255,.38)}\n.product-dots{position:absolute;left:50%;bottom:clamp(28px,4.5svh,52px);z-index:5;display:flex;align-items:center;gap:8px;transform:translateX(-50%);opacity:0;pointer-events:none;transition:opacity 360ms ease}\n.product-dot{width:34px;height:3px;padding:0;border:0;border-radius:999px;background:rgba(255,255,255,.3);opacity:1;cursor:pointer;transition:background 280ms ease,opacity 280ms ease,transform 360ms var(--ease)}\n.product-dot:hover{background:rgba(255,255,255,.55)}\n.product-dot.is-active{background:#fff;transform:scaleX(1.08)}'''
if old not in c: raise SystemExit('carousel css block not found')
c=c.replace(old,new,1)
c=c.replace('.coffee-slide.is-detail .coffee-layout{height:auto;min-height:220svh;align-items:start}', '.coffee-slide.is-detail .coffee-layout{height:auto;min-height:100svh;align-items:start}',1)
c=c.replace('.coffee-slide.is-detail .coffee-copy{position:sticky;top:0;align-self:start;height:auto;min-height:100svh;overflow:visible;padding:180px 5vw 72px 0}', '.coffee-slide.is-detail .coffee-copy{position:sticky;top:0;align-self:start;height:max-content;min-height:0;overflow:visible;padding:180px 5vw 72px 0}',1)
c=c.replace('.coffee-slide.is-detail .coffee-layout{display:block;min-height:250svh}', '.coffee-slide.is-detail .coffee-layout{display:block;min-height:100svh}',1)
c=c.replace('.coffee-slide.is-detail .coffee-copy{position:relative;left:auto;right:auto;bottom:auto;height:auto;min-height:114svh;padding:110px 20px 64px;text-align:left}', '.coffee-slide.is-detail .coffee-copy{position:relative;left:auto;right:auto;bottom:auto;height:auto;min-height:0;padding:110px 20px 64px;text-align:left}',1)
c=c.replace('.coffee-slide.is-detail .product-dots{bottom:18px}', '.coffee-slide.is-detail .product-dots{bottom:18px}.coffee-slide.is-detail .carousel-arrow{width:44px;height:44px;opacity:.72}.coffee-slide.is-detail .carousel-arrow--prev{left:16px}.coffee-slide.is-detail .carousel-arrow--next{right:16px}',1)
css.write_text(c)
