(()=>{
  const main=document.getElementById('cinematic-scroll');
  const stage=document.querySelector('.stage');
  const hero=document.querySelector('.hero__content');
  const heroSubtitle=document.querySelector('.hero__subtitle');
  const scrollCue=document.querySelector('.scroll-cue');
  const story=document.querySelector('.story__copy');
  const panels=[...document.querySelectorAll('.coffee-panel')];
  if(!main||!stage||!hero||!story||!panels.length)return;
  const brazil=panels[0];
  const items=panels.map(panel=>({panel,product:panel.querySelector('.product'),copy:panel.querySelector('.product-copy')}));
  const brazilProduct=items[0].product;
  const brazilCopy=items[0].copy;
  const brazilImage=brazilProduct?.querySelector('img');
  const brazilDescription=brazil.querySelector('.product-copy__description');
  const INTRO='#3d5825';
  const COLORS=['#4D6E48','#1C6E95','#563B66','#CF9A35','#634227','#332016'];
  const DURATION=1000;
  const MORPH=900;
  const EASE='cubic-bezier(.22,1,.36,1)';
  const PRODUCT_IMAGES={brazil:{Ground:'./assets/product_images/giannos-brazil-roast/Giannos Brazil Roast/giannos-brazil-ground-front.png','Whole Bean':'./assets/product_images/giannos-brazil-roast/Giannos Brazil Roast/giannos-brazil-whole-front.png'},'french-vanilla':'./assets/product_images/giannos-french-vanilla/Giannos French Vanilla/giannos-french-vanilla-ground-front.png','colombian-roast':'./assets/product_images/giannos-colombian-roast/Giannos Colombian Roast/giannos-colombia-ground-front.png','original-roast':'./assets/product_images/giannos-original-roast/Giannos Original Roast/giannos-original-ground-front.png',hazelnut:'./assets/product_images/giannos-hazelnut/Giannos Hazelnut/giannos-hazelnut-ground-front.png','espresso-roast':'./assets/product_images/giannos-espresso-roast/Giannos Espresso Roast/giannos-espresso-whole-front.png'};
  const state={mode:'intro',active:0,locked:false,detail:false};
  let wheelOpen=true,wheelTimer=null,pendingDirection=0;
  const clamp=(v,min=0,max=1)=>Math.min(Math.max(v,min),max);
  const map=(p,a,b)=>clamp((p-a)/(b-a));
  const lerp=(a,b,t)=>a+(b-a)*t;
  const maxScroll=()=>Math.max(main.offsetHeight-innerHeight,1);
  const scrollProgress=()=>clamp(scrollY/maxScroll());
  const transition=`transform ${DURATION}ms ${EASE},opacity ${DURATION}ms ${EASE},filter ${DURATION}ms ${EASE}`;
  function setBg(color){stage.style.backgroundColor=color;document.body.style.backgroundColor=color;document.documentElement.style.backgroundColor=color}
  function positionScrollCue(){if(!heroSubtitle||!scrollCue)return;const subtitleBottom=hero.offsetTop+heroSubtitle.offsetTop+heroSubtitle.offsetHeight,midpoint=subtitleBottom+(innerHeight-subtitleBottom)/2;scrollCue.style.top=`${Math.round(midpoint-scrollCue.offsetHeight/2)}px`}
  function loadImages(){if(brazilImage)brazilImage.src=PRODUCT_IMAGES.brazil.Ground;document.querySelectorAll('[data-coffee-image]').forEach(img=>{const src=PRODUCT_IMAGES[img.dataset.coffeeImage];if(src)img.src=src})}
  function productTarget(){if(innerWidth<=640)return 'translate(-50%,-62%) scale(.78)';return 'translate(calc(-50% - 25vw),-50%) scale(1)'}
  function copyTarget(){return innerWidth<=640?'translateY(0)':'translate(0,-50%)'}
  function resetCoffeeDom(){panels.forEach((panel,index)=>{panel.style.transition='none';panel.style.display='block';panel.style.visibility='visible';panel.style.opacity='0';panel.style.filter='blur(14px)';panel.style.transform=index===0?'translateX(0)':'translateX(105vw)';panel.style.pointerEvents='none';panel.style.zIndex='2';const {product,copy}=items[index];if(product){product.style.transition='none';product.style.visibility='visible';product.style.opacity='0';product.style.filter='blur(18px)';product.style.transform='translate(-50%,-50%) scale(.65)'}if(copy){copy.style.transition='none';copy.style.visibility='visible';copy.style.opacity='0';copy.style.filter='blur(18px)';copy.style.transform=innerWidth<=640?'translateY(70px)':'translate(22vw,-50%)'}})}
  function renderIntro(){if(state.mode!=='intro')return;const p=scrollProgress(),heroOut=map(p,.08,.32),storyIn=map(p,.38,.64);hero.style.transition='none';story.style.transition='none';hero.style.opacity=String(1-heroOut);hero.style.filter=`blur(${lerp(0,20,heroOut)}px)`;hero.style.transform=`translateY(${lerp(0,-72,heroOut)}px) scale(${lerp(1,.975,heroOut)})`;story.style.opacity=String(storyIn);story.style.filter=`blur(${lerp(20,0,storyIn)}px)`;story.style.transform=`translateY(${lerp(70,0,storyIn)}px) scale(${lerp(.98,1,storyIn)})`;setBg(INTRO)}
  function applyCoffeePanel(index,position){const {panel,product,copy}=items[index],active=position==='active';panel.style.display='block';panel.style.visibility='visible';panel.style.transition=transition;panel.style.zIndex=active?'6':'2';panel.style.pointerEvents=active?'auto':'none';panel.style.opacity=active?'1':'0';panel.style.filter=active?'blur(0)':'blur(14px)';panel.style.transform=active?'translateX(0)':position==='before'?'translateX(-105vw)':'translateX(105vw)';if(product){product.style.visibility='visible';product.style.transition=transition;product.style.opacity=active?'1':'0';product.style.filter=active?'blur(0)':'blur(16px)';product.style.transform=active?productTarget(index):position==='before'?'translate(calc(-50% - 50vw),-50%) scale(.9)':'translate(calc(-50% + 34vw),-50%) scale(.9)'}if(copy){copy.style.visibility='visible';copy.style.transition=transition;copy.style.opacity=active?'1':'0';copy.style.filter=active?'blur(0)':'blur(16px)';copy.style.transform=active?copyTarget():position==='before'?'translate(-18vw,-50%)':'translate(22vw,-50%)'}}
  function renderCoffee(){if(state.mode!=='coffee'||state.detail)return;panels.forEach((_,index)=>applyCoffeePanel(index,index===state.active?'active':index<state.active?'before':'after'));setBg(COLORS[state.active])}
  function unlock(){state.locked=false;if(!pendingDirection)return;const dir=pendingDirection;pendingDirection=0;stepCoffee(dir)}
  function enterCoffee(){if(state.mode!=='intro'||state.locked)return;state.mode='coffee';state.active=0;state.locked=true;story.style.transition=transition;story.style.opacity='0';story.style.filter='blur(18px)';story.style.transform='translateY(-90px) scale(.98)';panels.forEach((_,index)=>applyCoffeePanel(index,index===0?'active':'after'));setBg(COLORS[0]);setTimeout(unlock,DURATION)}
  function leaveCoffee(){if(state.mode!=='coffee'||state.active!==0||state.detail||state.locked)return;state.locked=true;const {panel,product,copy}=items[0];panel.style.transition=transition;panel.style.opacity='0';panel.style.filter='blur(14px)';if(product){product.style.transition=transition;product.style.opacity='0';product.style.filter='blur(18px)';product.style.transform='translate(-50%,-50%) scale(.65)'}if(copy){copy.style.transition=transition;copy.style.opacity='0';copy.style.filter='blur(18px)';copy.style.transform=innerWidth<=640?'translateY(70px)':'translate(22vw,-50%)'}story.style.transition=transition;story.style.opacity='1';story.style.filter='blur(0)';story.style.transform='translateY(0) scale(1)';setBg(INTRO);setTimeout(()=>{state.mode='intro';state.active=0;state.locked=false;pendingDirection=0;resetCoffeeDom();scrollTo(0,maxScroll()*.64);renderIntro()},DURATION)}
  function stepCoffee(direction){if(state.mode!=='coffee'||state.detail)return;if(state.locked){pendingDirection=direction;return}if(direction<0&&state.active===0){leaveCoffee();return}const next=state.active+direction;if(next<0||next>=panels.length)return;state.active=next;state.locked=true;renderCoffee();setTimeout(unlock,DURATION)}
  function wheelDirection(e){if(Math.abs(e.deltaY)<3)return 0;clearTimeout(wheelTimer);wheelTimer=setTimeout(()=>{wheelOpen=true},150);if(!wheelOpen)return 0;wheelOpen=false;return e.deltaY>0?1:-1}
  function onWheel(e){if(state.detail)return;if(state.mode==='intro'){if(scrollProgress()>=.70&&e.deltaY>0){e.preventDefault();enterCoffee()}return}e.preventDefault();const dir=wheelDirection(e);if(dir)stepCoffee(dir)}
  let scrollRaf=0;function onScroll(){if(state.mode!=='intro'||state.detail)return;cancelAnimationFrame(scrollRaf);scrollRaf=requestAnimationFrame(renderIntro)}
  function animateVertical(before,done){const els=[brazilProduct,brazilCopy],animations=[];els.forEach((el,index)=>{if(!el||!before[index])return;const after=el.getBoundingClientRect(),dy=before[index].top-after.top;if(Math.abs(dy)<1)return;animations.push(el.animate([{translate:`0 ${dy}px`},{translate:'0 0'}],{duration:MORPH,easing:EASE,fill:'both'}))});Promise.all(animations.map(a=>a.finished.catch(()=>{}))).then(()=>{animations.forEach(a=>a.cancel());done?.()})}
  const afterLayout=cb=>requestAnimationFrame(()=>requestAnimationFrame(cb));
  function collapseDescription(collapsed){if(!brazilDescription)return;brazilDescription.style.transition=`opacity ${MORPH}ms ${EASE},transform ${MORPH}ms ${EASE},max-height ${MORPH}ms ${EASE},margin ${MORPH}ms ${EASE}`;if(collapsed){brazilDescription.style.maxHeight='0';brazilDescription.style.marginTop='0';brazilDescription.style.opacity='0';brazilDescription.style.transform='translateY(-28px)';brazilDescription.style.overflow='hidden'}else{brazilDescription.style.maxHeight='220px';brazilDescription.style.marginTop='24px';brazilDescription.style.opacity='1';brazilDescription.style.transform='translateY(0)';brazilDescription.style.overflow='hidden'}}
  function openDetail(e){e?.preventDefault();if(state.mode!=='coffee'||state.active!==0||state.detail)return;const before=[brazilProduct?.getBoundingClientRect(),brazilCopy?.getBoundingClientRect()];state.detail=true;document.body.classList.add('detail-open');brazil.classList.add('is-detail');brazil.style.zIndex='10';brazil.style.opacity='1';brazil.style.transform='translateX(0)';if(brazilProduct){brazilProduct.style.transition='none';brazilProduct.style.opacity='1';brazilProduct.style.filter='blur(0)';brazilProduct.style.transform='translateX(-50%)'}if(brazilCopy){brazilCopy.style.transition='none';brazilCopy.style.opacity='1';brazilCopy.style.filter='blur(0)';brazilCopy.style.transform='none';if(innerWidth>840){brazilCopy.style.top='0';brazilCopy.style.height='100svh';brazilCopy.style.paddingTop='32px';brazilCopy.style.paddingBottom='32px'}}afterLayout(()=>{animateVertical(before);requestAnimationFrame(()=>collapseDescription(true))})}
  function closeDetail(){if(!state.detail)return;const before=[brazilProduct?.getBoundingClientRect(),brazilCopy?.getBoundingClientRect()];state.detail=false;collapseDescription(false);document.body.classList.remove('detail-open');if(brazilCopy){brazilCopy.style.top='';brazilCopy.style.height='';brazilCopy.style.paddingTop='';brazilCopy.style.paddingBottom=''}brazil.classList.remove('is-detail');applyCoffeePanel(0,'active');afterLayout(()=>animateVertical(before,()=>{setTimeout(()=>{if(!brazilDescription)return;brazilDescription.style.transition='';brazilDescription.style.maxHeight='';brazilDescription.style.marginTop='';brazilDescription.style.opacity='';brazilDescription.style.transform='';brazilDescription.style.overflow=''},80)}))}
  const purchaseCards=[...document.querySelectorAll('[data-purchase-card]')],bagOptions=[...document.querySelectorAll('.bag-option')],grindOptions=[...document.querySelectorAll('.choice-tab')],subscribeOriginal=document.querySelector('[data-subscribe-original]'),subscribePrice=document.querySelector('[data-subscribe-price]'),oneTimePrice=document.querySelector('[data-one-time-price]'),cartTotal=document.querySelector('[data-cart-total]'),qtyLabel=document.querySelector('[data-qty]');let purchaseMode='subscribe',bagCount=1,discount=10,qty=1;const money=v=>`$${v.toFixed(2)}`;
  function updatePurchase(){const original=20*bagCount,subscription=original*(1-discount/100),total=(purchaseMode==='subscribe'?subscription:original)*qty;if(subscribeOriginal)subscribeOriginal.textContent=money(original);if(subscribePrice)subscribePrice.textContent=money(subscription);if(oneTimePrice)oneTimePrice.textContent=money(original);if(cartTotal)cartTotal.textContent=money(total);if(qtyLabel)qtyLabel.textContent=qty;purchaseCards.forEach(card=>{const selected=card.dataset.purchaseCard===purchaseMode;card.classList.toggle('is-selected',selected);const icon=card.querySelector('.radio-icon');if(icon)icon.textContent=selected?'radio_button_checked':'radio_button_unchecked'})}
  document.querySelectorAll('[data-purchase]').forEach(button=>button.addEventListener('click',()=>{purchaseMode=button.dataset.purchase;updatePurchase()}));bagOptions.forEach(button=>button.addEventListener('click',()=>{bagCount=Number(button.dataset.bags);discount=Number(button.dataset.discount);bagOptions.forEach(item=>item.classList.toggle('is-selected',item===button));updatePurchase()}));grindOptions.forEach(button=>button.addEventListener('click',()=>{grindOptions.forEach(item=>item.classList.toggle('is-selected',item===button));const src=PRODUCT_IMAGES.brazil[button.dataset.grind];if(brazilImage&&src)brazilImage.src=src}));document.querySelector('[data-qty-minus]')?.addEventListener('click',()=>{qty=Math.max(1,qty-1);updatePurchase()});document.querySelector('[data-qty-plus]')?.addEventListener('click',()=>{qty+=1;updatePurchase()});document.querySelector('[data-open-product]')?.addEventListener('click',openDetail);document.querySelector('[data-close-product]')?.addEventListener('click',closeDetail);document.querySelectorAll('.product-copy__details:not([data-open-product])').forEach(link=>link.addEventListener('click',e=>e.preventDefault()));
  addEventListener('scroll',onScroll,{passive:true});addEventListener('wheel',onWheel,{passive:false});addEventListener('resize',()=>{positionScrollCue();if(state.mode==='intro')renderIntro();else if(state.mode==='coffee'&&!state.detail)renderCoffee()});addEventListener('keydown',e=>{if(state.detail){if(e.key==='Escape')closeDetail();return}if(state.mode!=='coffee')return;if(e.key==='ArrowDown'||e.key==='PageDown'){e.preventDefault();stepCoffee(1)}if(e.key==='ArrowUp'||e.key==='PageUp'){e.preventDefault();stepCoffee(-1)}});
  history.scrollRestoration='manual';document.body.classList.remove('detail-open');brazil.classList.remove('is-detail');loadImages();updatePurchase();positionScrollCue();setBg(INTRO);resetCoffeeDom();scrollTo(0,0);renderIntro();document.fonts?.ready.then(positionScrollCue);
})();